bllog/urls.py
from django.urls import path
from blog.views import (
	create_blog_view,
	detail_blog_view,
	edit_blog_view,
)

app_name = 'blog'

urlpatterns = [
    path('create/', create_blog_view, name="create"),
    path('<slug>/', detail_blog_view, name="detail"),
    path('<slug>/edit/', edit_blog_view, name="edit"),
 ]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
# from django.conf.urls import url
from uploader import views
from blog import urls
#from accountss import urls
from accountss.views import registration_view, logout_view,login_view,account_view,must_authenticate_view
from blog.views import create_blog_view,detail_blog_view,edit_blog_view,get_blog_queryset

from personal.views import home_screen_view
# from accountss import urls

#from django.conf.urls import url

# from mysite import settings






from . import views


from django.views.generic import TemplateView
admin.site.site_header= "Project Progress Website"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.realhomepage),
    #path('', TemplateView.as_view(template_name="homepage.html"), name="realhomepage"),
    path('old-home', TemplateView.as_view(template_name="Home.html")),
    path('home', views.home),
    path('firstview', TemplateView.as_view(template_name="firstview.html")),
    path('progress', views.progress),
    path('progress/', include('progress.urls')),
    path('test/', views.test),
    path('navigation/', views.navigation),
    path('links/', views.navigation),
   path('veriosn', TemplateView.as_view(template_name="versions.html")),
   path('accounts/', include('allauth.urls')),
    re_path(r'^theuploader/$', views.main, name='main'),
    #url(r'/^$', views.main, name='main'),
    re_path(r'^uploader/media/$', views.simple_upload, name='simple_upload'),
    path('dev-tools', TemplateView.as_view(template_name="dev-tools.html")), 
    path('navigation', TemplateView.as_view(template_name="navigation.html")),
    path('navigation/specific-header', TemplateView.as_view(template_name="specific-header.html")),
    path('ml/', TemplateView.as_view(template_name="logedin.html")),
  path('CSerror', views.CSRF_ERROR),
  path('munchy2', TemplateView.as_view(template_name="logon2.html")),
  path('munchy3', TemplateView.as_view(template_name="logon3.html")),
  path('blogs/', include('blog.urls')),
  # path('accountss/', include('accountss.urls')),
   # url(r'^upload-tool/$', views.main, name='main'),
  #  url(r'^uploader/media/$', views.simple_upload, name='simple_upload'),
   # url(r'^media/documents/test.txt$', views.main, name='simple_upload'),
   # url(r'^main/$', views.main, name='main'),
   # url(r'^downloads/$', views.simple_upload, name='simple_upload'),
   path('blogs/', home_screen_view, name="home"),
    path('blogss/account/', account_view, name="account"),
    path('blogs/admin/', admin.site.urls),
    path('blog/', include('blog.urls', 'blog')),
    path('blogs/login/', login_view, name="login"),
    path('blogs/logout/', logout_view, name="logout"),
	path('blogs/must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('blogs/register/', registration_view, name="register"),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    #path('blogs/password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        #name='password_change_done'),

    #path('blogs/password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        #name='password_change'),

    #path('blogs/password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     #name='password_reset_done'),

    #path('blogs/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    #path('blogs/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    #path('blogs/reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     #name='password_reset_complete'),
]


if settings.DEBUG==True:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
   #urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_URL)
   #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 # how can we implement this: https://www.youtube.com/watch?v=v5FWAxi5QqQ look at timestamp 7:18. I dont know how to implement that in html. #no idea help 
  
    
    #path('home/', ) # this wont work i think.
  

    

       

bllog/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete
from django.dispatch import receiver

def upload_location(instance, filename):
	file_path = 'blog/{author_id}/{title}-{filename}'.format(
				author_id=str(instance.author.id),title=str(instance.title), filename=filename)
	return file_path


class BlogPost(models.Model):
	title 					= models.CharField(max_length=50, null=False, blank=False)
	body 					= models.TextField(max_length=5000, null=False, blank=False)
	image		 			= models.ImageField(upload_to=upload_location, null=True, blank=True)
	date_published 			= models.DateTimeField(auto_now_add=True, verbose_name="date published")
	date_updated 			= models.DateTimeField(auto_now=True, verbose_name="date updated")
	author 					= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	slug 					= models.SlugField(blank=True, unique=True)

	def __str__(self):
		return self.title

@receiver(post_delete, sender=BlogPost)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False) 

def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = slugify(instance.author.username + "-" + instance.title)

pre_save.connect(pre_save_blog_post_receiver, sender=BlogPost)

bllog/forms.py
from django import forms

from blog.models import BlogPost 


class CreateBlogPostForm(forms.ModelForm):

	class Meta:
		model = BlogPost
		fields = ['title', 'body', 'image']


class UpdateBlogPostForm(forms.ModelForm):

	class Meta:
		model = BlogPost
		fields = ['title', 'body', 'image']

	def save(self, commit=True):
		blog_post = self.instance
		blog_post.title = self.cleaned_data['title']
		blog_post.body = self.cleaned_data['body']

		if self.cleaned_data['image']:
			blog_post.image = self.cleaned_data['image']

		if commit:
			blog_post.save()
		return blog_post

bllog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.http import HttpResponse

from blog.models import BlogPost
from blog.forms import CreateBlogPostForm, UpdateBlogPostForm
#from account.models import Account
# i killed it 
from accountss.models import Account
from accountss.views import must_authenticate_view
def create_blog_view(request):

	context = {}
# don not change anything below I am working on the thingy you want to change. 
  #can i run djanog 3.2.11
  # sure idc.
	user = request.user
	if not user.is_authenticated:
		return render(request, 'account/must_authenticate.html', {})
	form = CreateBlogPostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		obj = form.save(commit=False)
		#author = Account.objects.filter(email=user.username).first()
    #author = request.user
		obj.author = request.user
    
		obj.save()
		form = CreateBlogPostForm()

	context['form'] = form

	return render(request, "blog/create_blog.html", context)


def detail_blog_view(request, slug):

	context = {}

	blog_post = get_object_or_404(BlogPost, slug=slug)
	context['blog_post'] = blog_post

	return render(request, 'blog/detail_blog.html', context)



def edit_blog_view(request, slug):

	context = {}

	user = request.user
	if not user.is_authenticated:
		return redirect("must_authenticate")

	blog_post = get_object_or_404(BlogPost, slug=slug)

	if blog_post.author != user:
		return HttpResponse('You are not the author of that post.')

	if request.POST:
		form = UpdateBlogPostForm(request.POST or None, request.FILES or None, instance=blog_post)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save()
			context['success_message'] = "Updated"
			blog_post = obj

	form = UpdateBlogPostForm(
			initial = {
					"title": blog_post.title,
					"body": blog_post.body,
					"image": blog_post.image,
         # "author1": blog_post.author,
			}
		)

	context['form'] = form
	return render(request, 'blog/edit_blog.html', context)


def get_blog_queryset(query=None):
	queryset = []
	queries = query.split(" ") # python install 2019 = [python, install, 2019]
	for q in queries:
		posts = BlogPost.objects.filter(
				Q(title__icontains=q) | 
				Q(body__icontains=q) 
       # Q(author1__icontains=q)        
			).distinct()

		for post in posts:
			queryset.append(post)

	return list(set(queryset))	

bllog/templates/blog/snippets/blog_post_pagination.html
<!-- FILTERED Pagination -->
<div class="d-flex flex-column m-auto pagination mt-5">
<nav aria-label="Page navigation">
<ul class="pagination pg-grey justify-content-center">
	{% if blog_posts.has_previous %}
        <li class="page-item ">
		  <a class="bg-dark text-light page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.previous_page_number }}">&laquo; Previous</a>
		</li>
    {% endif %}

	{% for i in blog_posts.paginator.page_range %}
		{% if blog_posts.number == i %}
			<li class="bg-dark text-light page-item active"><a class="page-link bg-dark text-light">{{ i }}</a></li>
		{% else %}
			<li class="bg-dark text-light page-item" ><a class="bg-dark text-light page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ i }}">{{ i }}</a></li>
		{% endif %}
	{% endfor %}
    
    {% if blog_posts.has_next %}
    	<li class="page-item">
		  <a class="bg-dark text-light page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.next_page_number }}">Next</a>
		</li>
		<li class="page-item">
		  <a class="page-link bg-dark text-light"  href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.paginator.num_pages }}">Last &raquo;</a>
		</li>
    {% endif %}
</ul>
</nav>
</div>
<!-- end pagination-->

bllog/templates/blog/snippets/blog_post_snippet.html
<style type="text/css">
	.card{
		max-width: 700px;
		width: 100%;
	}
	.card-body{
		padding: 20px;
	}
</style>

{% if blog_post %}
<div class="container">
	<div class="row bg-dark">
		<!-- Blog Post -->
		<div class="card m-auto text-light bg-dark">
			<a href="{% url 'blog:detail' post.slug %}">
				{% if blog_post.image %}
        <img class="card-img-top" src="{{blog_post.image.url}}">
        {% endif %}
			</a>
			<div class="card-body mt-2 mb-2">
				<a href="{% url 'blog:detail' post.slug %}">
					<h2 class="card-title">{{blog_post.title}}</h2>
				</a>
				<p class="card-text">{{blog_post.body|safe|truncatechars:180}}</p>
				{% if blog_post.author == request.user %}
					<a href="{% url 'blog:edit' blog_post.slug %}" class="btn btn-primary">Update</a>
				{% endif %}
       <!-- <br>
         add mt-2 if nessecary -->
        <a href="/answers" class=" btn btn-primary">Check for replies</a>
			</div>
			<div class="card-footer text-muted">
			  Updated on {{blog_post.date_updated}} by {{blog_post.author.username}}
			</div>
		</div>
	</div>
</div>

{% else %}

<div class="container">
	<div class="row">
		<div class="card m-auto bg-dark">
			<div class="card-body mt-2 mb-2">
				<h2 class="card-title text-light ">No results</h2>
				<p class="card-text text-light">There were no results matching the search: "{{query}}"</p>
			</div>
		</div>
	</div>
</div>

{% endif %}